PSR-4 and single namespace
scrivo/highlight.php pull request #77
Opened 2020-09-16 03:25 UTC by phpfui

This is a start of the V10 release.  Single Highlight namespace.  \HighlightUtilities\ can be changed to \Highlight\Utilities:: for backward compatibility.

- Moved to PSR-4 autoloading and src directory containing all needed files (languages and styles)
- Removed some things marked depreciated for V10
- Removed _internals.php (getNoCssExtension  now in Utilities as private)
- Removed Autoloader.php as it is old school
- Added Utilities::getLanguageFolder and used it in unit tests to abstract the path changes
- Changed unit tests and demo to use composer autoload.php

Unit tests are failing in this branch, but they seem to fail exactly the same way as in master branch, so maybe a Windows pathing issue if they run under nix.

**ToDo:**

- Update to PHP 7.1 or higher
- Update composer with PHP version
- Update PHPUnit
- Use Rector to add parameter and return types
- Still a few @todo items to address

2020-10-08 03:29 UTC, allejo requested changes
This looks good for restructuring!

Can you please restore the `HighlightUtilities` namespace, I think it's best to keep custom functionality away from the core port?

As for the rest of the todos, let's hold off on them for now.

2020-10-09 01:36 UTC, phpfui commented
I put back the HightlightUtilities namespace, but left the static class, as it is better for autoloading with PSR-0.  I also added function stubs that call into the Functions static class, so we have the best of both worlds, backward compatibility, and a path to just class based source.

Maybe the stand alone functions should be marked as depreciated.

Also unit tests are failing for me, but might be a Windows issue. But they fail in the same way as the main branch.

This is a great base for V10.  And thanks for allowing me to do the /src dirrectory.  This is a major improvement and aligns the library with best practices.

2020-10-10 21:23 UTC, allejo approved these changes

2020-10-10 21:24 UTC, allejo commented
I'll keep the `HighlightUtilities\Functions` class and remove the stand-alone functions for now. I'll come back to that decision later.

But thank you for this PR! :smile:

2020-10-10 21:24 UTC, merged